### PR TITLE
IPS defaults adjustment

### PR DESCRIPTION
**Pull request by joao-luna-98**

### CODE REVIEW

**Comment by joaomlourenco** [comment]
The file with the image "ESTS-JPG.jpg " is missing in the commit.  Please add it and resubmit. Thanks.

**Comment by joao-luna-98** [comment]
It's in the images folder inside the ests folder.

**Comment by joaomlourenco** [comment]
I can't find it in the request. Did you "git add" it before committing and submitting the pull request?

**Comment by joaomlourenco** [comment]
Maybe you can send it to me by email and I'll add it myself.  Thanks.

**Comment by joao-luna-98** [comment]
I'm pretty sure it was already there before this commit. 
image
As you can see it was there 3 days ago, in the develop branch.

**Comment by joaomlourenco** [comment]
Sorry. My mistake.  :(

**Comment by joaomlourenco** [comment]
You have this in "template.tex".  Not working… what did you mean with this?

```
% PhD    configuration
\PhD   fontsize{\small\itshape}
\setlength\PhD   width{12.5cm}
\setlength\PhD   rule{0pt}
```

**Comment by joao-luna-98** [comment]
I only changed the defaults file

**Comment by joaomlourenco** [comment]
Again, my mistake.  Pull request is available in the develop branch.  Soon will migrate to master branch. Thank you.  Please don't hesitate in collaborating more…  :)

**Pull request merged**
